name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - name: Setup Node
        uses: josh-development/.github/setup-node@main
      - name: Add ESLint Problem Matcher
        run: echo "::add-matcher::.github/problemMatchers/eslint.json"
      - name: Run ESLint
        run: yarn lint --fix=false
      - name: Add TypeScript Problem Matcher
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"
      - name: Compile Source Code
        run: yarn build
      - name: Generate Documentation
        run: yarn docs
      - name: Run Tests
        run: yarn test --coverage
      - name: Store Code Coverage Report
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: coverage
          path: coverage/

  upload-coverage-report:
    name: Upload Code Coverage Report
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          fetch-depth: 2
      - name: Download Coverage Report
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: coverage
          path: coverage/
      - name: Codecov Upload
        uses: codecov/codecov-action@40a12dcee2df644d47232dde008099a3e9e4f865 # v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage/
          fail_ci_if_error: true
