name: NPM Deprecate PR On Merge

on:
  pull_request:
    types:
      - closed

jobs:
  deprecate-on-merge:
    name: NPM Deprecate PR On Merge
    runs-on: ubuntu-latest

    if: github.repository_owner == 'josh-development'
    steps:
      - name: Checkout Project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup Node
        uses: josh-development/.github/setup-node@main
      - name: Deprecate versions
        run: yarn npm-deprecate --name "*pr-${PR_NUMBER}*" -d -v
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
