name: Documentation

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest

    if: github.repository_owner == 'josh-development'
    outputs:
      NAME: ${{ steps.env.outputs.NAME }}
      TYPE: ${{ steps.env.outputs.TYPE }}
      SHA: ${{ steps.env.outputs.SHA }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Setup Node
        uses: josh-development/.github/setup-node@main
      - name: Build Documentation
        run: yarn docs
      - name: Upload Documentation Artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: docs
          path: docs/api.json
      - name: Set Output
        id: env
        run: |
          echo "::set-output name=NAME::${GITHUB_REF_NAME}"
          echo "::set-output name=TYPE::${GITHUB_REF_TYPE}"
          echo "::set-output name=SHA::${GITHUB_SHA}"
  upload:
    name: Upload Documentation
    needs: build
    runs-on: ubuntu-latest
    env:
      NAME: ${{ needs.build.outputs.NAME }}
      TYPE: ${{ needs.build.outputs.TYPE }}
      SHA: ${{ needs.build.outputs.SHA }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Use Node.js v16
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Download Documentation Artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: docs
          path: docs
      - name: Checkout Documentation Project
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          repository: 'josh-development/docs'
          token: ${{ secrets.ACCESS_TOKEN }}
          path: 'out'

      - name: Move Documentation
        if: ${{ env.TYPE == 'tag' }}
        env:
          SEMVER: ${{ env.NAME }}
        run: |
          mkdir -p out/core
          mv docs/api.json out/core/${SEMVER}.json
      - name: Move Documentation
        if: ${{ env.TYPE == 'branch' }}
        run: |
          mkdir -p out/core
          mv docs/api.json out/core/${NAME}.json

      - name: Commit & Push
        run: |
          cd out
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config rebase.autostash true
          git config pull.rebase true
          git add .
          git commit -m "docs(core): build for ${TYPE} ${NAME}: ${SHA}" || true
          git pull
          git push
